In [154]:
import numpy as np

In [155]:
class QLearning:

    def __init__(self):
        self.q_table    = np.zeros((2, 2))
        self.discount   = 0.8
        self.learn_rate = 0.2
        
    def decision(self, prot):
        self.state = prot
        
        if self.q_table[self.state, 0] == self.q_table[self.state, 1]:
            action = np.random.randint(2)
        else:
            action = np.argmax(self.q_table[self.state, :])
        
        self.action = action
        self.state_new = action
        
        return action
    
    def update_qtable(self, reward):
        self.q_table[self.state, self.action] = (1. - self.learn_rate) * self.q_table[self.state, self.action] + \
                        self.learn_rate * (reward + self.discount * np.max(self.q_table[self.state_new, :]))
        
        return

In [156]:
filename = "/home/andre/UFMG/SOMAC-ML/data/23092018/round2/somac/backlog_file.npy"
data = np.load(filename, encoding = "latin1").item()

In [157]:
ql = QLearning()

reward = 0
tsteps = [t for t in range(len(data) - 1)]

for t in data:
    prot = data[t]["prot"]
    decision = ql.decision(prot)
    
    print("t = {},\t\tdecision = {}".format(t, decision))
    
    if prot == decision:
        reward = 1. * (data[t]["metrics"][0, 0] / (1. + data[t]["metrics"][4, 0]) - reward)
    else:
        reward = 2. * (data[t]["metrics"][0, 0] / (1. + data[t]["metrics"][4, 0]) - reward)
    thr = data[t]["metrics"][0, 1]
    
    ql.update_qtable(reward)
    print(ql.q_table)
    print("----")

t = 0,		decision = 1
[[0.         0.01323659]
 [0.         0.        ]]
----
t = 1,		decision = 1
[[ 0.         -0.00439048]
 [ 0.          0.        ]]
----
t = 2,		decision = 0
[[ 0.0213505  -0.00439048]
 [ 0.          0.        ]]
----
t = 3,		decision = 0
[[ 0.00755999 -0.00439048]
 [ 0.          0.        ]]
----
t = 4,		decision = 0
[[ 0.02623233 -0.00439048]
 [ 0.          0.        ]]
----
t = 5,		decision = 0
[[ 0.0128351  -0.00439048]
 [ 0.          0.        ]]
----
t = 6,		decision = 0
[[ 0.02994565 -0.00439048]
 [ 0.          0.        ]]
----
t = 7,		decision = 0
[[ 0.01711628 -0.00439048]
 [ 0.          0.        ]]
----
t = 8,		decision = 0
[[ 0.03400896 -0.00439048]
 [ 0.          0.        ]]
----
t = 9,		decision = 0
[[ 0.02066291 -0.00439048]
 [ 0.          0.        ]]
----
t = 10,		decision = 0
[[ 0.03847296 -0.00439048]
 [ 0.          0.        ]]
----
t = 11,		decision = 0
[[ 0.02356842 -0.00439048]
 [ 0.          0.        ]]
----
t = 12,		decision = 0
[[ 0.042

In [158]:
ql.q_table

array([[ 0.04238056, -0.00439048],
       [-0.02884602,  0.07718221]])